{
 "bad": false,
 "new_version": "7.672.25036",
 "new_version_attempts": {
  "4.22.21108": 1,
  "5.18.21182": 1,
  "5.23.21182": 1,
  "7.114.22021": 1,
  "7.125.22022": 1,
  "7.132.22039": 1,
  "7.136.22057": 1,
  "7.137.22057": 1,
  "7.142.22057": 2,
  "7.148.22086": 1,
  "7.163.22119": 1,
  "7.173.22126": 0,
  "7.213.22307": 1,
  "7.230.22310": 2.4000000000000004,
  "7.238.22316": 1.2,
  "7.252.22317": 1.4,
  "7.271.22339": 0.19999999999999996,
  "7.279.22339": 3.200000000000001,
  "7.310.22362": 1,
  "7.331.23005": 0.5999999999999999,
  "7.341.23006": 7,
  "7.358.23070": 5,
  "7.365.23080": 4,
  "7.368.23092": 3,
  "7.378.23124": 8,
  "7.4.21313": 1,
  "7.403.23150": 3,
  "7.409.23162": 3,
  "7.417.23168": 12,
  "7.433.23235": 1,
  "7.434.23241": 6,
  "7.440.23265": 6,
  "7.450.23304": 5,
  "7.455.23316": 19,
  "7.475.24004": 1,
  "7.476.24007": 8,
  "7.492.24021": 3,
  "7.502.24024": 5,
  "7.508.24028": 4,
  "7.519.24031": 3,
  "7.520.24032": 3,
  "7.527.24034": 3,
  "7.530.24035": 0.19999999999999996,
  "7.531.24035": 1.5999999999999999,
  "7.541.24038": 3.200000000000001,
  "7.543.24046": 4.400000000000002,
  "7.547.24058": 3.0,
  "7.551.24062": 3.200000000000001,
  "7.562.24075": 2.2,
  "7.564.24076": 0.19999999999999996,
  "7.565.24076": 0.19999999999999996,
  "7.570.24076": 2.6000000000000005,
  "7.574.24078": 3.200000000000001,
  "7.578.24081": 4.000000000000001,
  "7.582.24095": 1.4000000000000001,
  "7.584.24095": 3.4000000000000004,
  "7.600.24114": 0.3999999999999999,
  "7.603.24115": 0.19999999999999996,
  "7.606.24115": 1,
  "7.611.24120": 0.3999999999999999,
  "7.613.24121": 0.19999999999999996,
  "7.615.24125": 0.19999999999999996,
  "7.621.24125": 0.19999999999999996,
  "7.623.24125": 2.6000000000000005,
  "7.627.24136": 1.9999999999999998,
  "7.632.24139": 12.399999999999999,
  "7.671.25036": 0.7999999999999998,
  "7.672.25036": 2.3999999999999995
 },
 "new_version_errors": {
  "7.230.22310": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3419656527\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-dots 9.230.22310.*\\n']",
  "7.238.22316": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3451776950\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-dots 9.238.22316.*\\n']",
  "7.252.22317": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3456881494\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-dots 9.251.22317.*\\n']",
  "7.271.22339": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3615889992\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-future 6.265.22338.*\\n  - nothing provides requested mo-dots 9.266.22338.*\\n']",
  "7.279.22339": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3770656772\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-dots 9.279.22339.*\\n']",
  "7.331.23005": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3847336493\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-dots 9.331.23005.*\\n']",
  "7.341.23006": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.341.23006' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.358.23070": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.358.23070' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.365.23080": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.365.23080' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.368.23092": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.368.23092' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.378.23124": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.378.23124' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.403.23150": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.403.23150' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.409.23162": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.409.23162' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.417.23168": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.417.23168' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.433.23235": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.433.23235' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.434.23241": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.434.23241' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.440.23265": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.440.23265' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.450.23304": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.450.23304' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.455.23316": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.455.23316' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.475.24004": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.475.24004' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.476.24007": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.476.24007' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.492.24021": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.492.24021' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.502.24024": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.502.24024' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.508.24028": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.508.24028' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.519.24031": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.519.24031' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.520.24032": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.520.24032' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.527.24034": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.527.24034' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz'\n",
  "7.530.24035": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/7776618202'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.530.24035.*  does not exist (perhaps a typo or a missing channel);\n\u2514\u2500 mo-future 7.520.24032.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.531.24035": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/7779660126'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 mo-dots 9.531.24035.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.541.24038": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/7857852038'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.541.24038.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.541.24038 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.543.24046": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8041470538'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.543.24046.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.541.24038 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.547.24058": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8076345051'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.547.24058.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.546.24057 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.551.24062": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8274474043'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.549.24062.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.546.24057 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.562.24075": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8309359068'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.562.24075.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.546.24057 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.564.24076": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8309944736'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 mo-dots 9.564.24076.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.565.24076": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8310520621'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 mo-dots 9.565.24076.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.570.24076": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8319523101'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.570.24076.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.546.24057 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.574.24078": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8356056129'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.574.24078.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.546.24057 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.578.24081": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8501280932'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.578.24081.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.546.24057 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.582.24095": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8552138705'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.582.24095.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.546.24057 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.584.24095": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8582259135'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 9.584.24095.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.584.24095 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.600.24114": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8798250814'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 mo-dots 9.600.24114.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.603.24115": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8821076975'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 mo-dots 9.603.24115.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.611.24120": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8876358127'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 10.611.24120.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.584.24095 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.613.24121": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8938047100'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 10.613.24121.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.584.24095 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.615.24125": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8952032952'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 mo-dots 10.615.24125.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.621.24125": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/8952712590'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 mo-dots 10.621.24125.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.623.24125": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9054010521'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 mo-dots 10.623.24125.*  is installable and it requires\n\u2502  \u2514\u2500 mo-future 7.584.24095 , which can be installed;\n\u2514\u2500 mo-future 7.531.24035.*  is not installable because it conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "7.627.24136": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9132283613'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Could not solve for environment specs\nThe following package could not be installed\n\u2514\u2500 mo-dots 10.627.24136.*  does not exist (perhaps a typo or a missing channel).\n                </pre>\n                </div>\n                </details>",
  "7.632.24139": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/9466294215\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 567, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run(\n                            ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 211, in run\n    migration_run_data = run_migration(\n                         ^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 63, in run_migration\n    return run_migration_containerized(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migration_runner.py\", line 136, in run_migration_containerized\n    logger.debug(f\"host feedstock dir {feedstock_dir}: {os.listdir(feedstock_dir)}\")\n                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/cf-scripts/cf-scripts/cf-graph/mo-kwargs-feedstock'\n",
  "7.671.25036": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/13166790360'>bot CI job</a>) @ main\n        <details>\n        <div align=\"left\">\n        <pre>\n        linux_64_: Cannot solve the request because of: mo-dots 10.671.25036.* cannot be installed because there are no viable options:\n\u2514\u2500 mo-dots 10.671.25036 would require\n   \u2514\u2500 mo-future ==7.671.25036, for which no candidates were found.\n\n        </pre>\n        </div>\n        </details>",
  "7.672.25036": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/13176195582\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 467, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 462, in _make_request\n    httplib_response = conn.getresponse()\n                       ^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 1395, in getresponse\n    response.begin()\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 325, in begin\n    version, status, reason = self._read_status()\n                              ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/http/client.py\", line 286, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/socket.py\", line 718, in readinto\n    return self._sock.recv_into(b)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/ssl.py\", line 1314, in recv_into\n    return self.read(nbytes, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/ssl.py\", line 1166, in read\n    return self._sslobj.read(len, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTimeoutError: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/adapters.py\", line 667, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 801, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/util/retry.py\", line 552, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/packages/six.py\", line 770, in reraise\n    raise value\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 715, in urlopen\n    httplib_response = self._make_request(\n                       ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 469, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 358, in _raise_timeout\n    raise ReadTimeoutError(\nurllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py\", line 201, in _request\n    return request_method(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 754, in get\n    return self._forward_request(self._session.get, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 746, in _forward_request\n    response = method(*args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/session.py\", line 171, in request\n    response = super().request(*args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/adapters.py\", line 713, in send\n    raise ReadTimeout(e, request=request)\nrequests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 744, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run_with_tmpdir(\n                            ^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 451, in run_with_tmpdir\n    return run(\n           ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 523, in run\n    if not _prepare_feedstock_repository(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 165, in _prepare_feedstock_repository\n    backend.fork(context.git_repo_owner, context.git_repo_name)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py\", line 81, in inner\n    return func(*args, **kwds)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 844, in fork\n    if self.does_repository_exist(self.user, repo_name):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 820, in does_repository_exist\n    self._get_repo(owner, repo_name)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 814, in _get_repo\n    raise e\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py\", line 804, in _get_repo\n    repo = self.github3_client.repository(owner, repo_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/github.py\", line 2103, in repository\n    json = self._json(self._get(url), 200)\n                      ^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py\", line 216, in _get\n    return self._request(\"get\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/github3/models.py\", line 206, in _request\n    raise exceptions.ConnectionError(exc)\ngithub3.exceptions.ConnectionError: <class 'requests.exceptions.ReadTimeout'>: A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)\n"
 }
}